# Generated by Django 4.1.1 on 2022-10-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('artist', models.CharField(max_length=60)),
                ('song', models.FileField(upload_to='mp3s')),
            ],
        ),
    ]
