# Generated by Django 4.1.1 on 2022-10-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_songmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='songmodel',
            name='end',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songmodel',
            name='start',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
